### PR TITLE
German and Portuguese(Brazil)

### PR DESCRIPTION
**Pull request by mmklug**

### CODE REVIEW

**Comment by jordibruin** [comment]
Thanks @mmklug , sorry it took a bit to merge this in!

**Comment by vickipetrova** [comment]
Hey 😊,
Thank you so much for translating Posture Pal 🦒! As promised here is your Promo Code for the Pro version: JM6EAHATEYE4 @mmklug

**Comment by vickipetrova** [comment]
Hi again!
We added a few more sentences that are used in the new version. We’d really appreciate it if you have some time to translate those as well! 😄 @mmklug

**Comment by vickipetrova** [comment]
Hi again @mmklug  ! 😊

Thank you for helping us make Posture Pal accessible in more languages. With our new update on the go, we’d really appreciate a bit of help to translate a few new strings. 🚀 German is only missing around 5 strings. And Portuguese (Brazil) is missing around 15 of them. We used a website to upload all the strings and screenshots of the app where the relevant strings are found to make the translation process easier for you! You can use this [link](https://crwd.in/posture-pal) to quickly make an account and fill out the missing strings. Thank you in advance and reach out if you have any other questions!

**Pull request merged**
