### PR TITLE
Added Hungarian Localizations

### PR DESCRIPTION
**Pull request by KristofKekesi**

### CODE REVIEW

**Comment by jordibruin** [comment]
Thanks a lot! If you have time later this week to also do the App Store text that would be even more amazing!
I forgot to commit that file 😅

**Comment by jordibruin** [comment]
I noticed I did not correctly localise 11 strings from the onboarding. I've added them to localisable file for you language if you could have a look! @KristofKekesi

**Comment by KristofKekesi** [comment]
Translated those as well with PR #19.

**Comment by vickipetrova** [comment]
Hey 😊,
Thank you so much for translating Posture Pal 🦒! As promised here is your Promo Code for the Pro version: RLYT79W9XFXJ @KristofKekesi

**Comment by KristofKekesi** [comment]
Thank you

**Comment by vickipetrova** [comment]
Hi again!
We added a few more sentences that are used in the new version. We’d really appreciate it if you have some time to translate those as well! 😄 @KristofKekesi

**Comment by KristofKekesi** [comment]
Ready to merge with #40! 🥳

**Pull request merged**
