### PR TITLE
Updated Hungarian localization

### PR DESCRIPTION
**Pull request by KristofKekesi**

### CODE REVIEW

**Comment by jordibruin** [comment]
Looks fantastic, thanks!

**Comment by vickipetrova** [comment]
Hi again @KristofKekesi ! 😊

Thank you for helping us make Posture Pal accessible in more languages. With our new update on the go, we’d really appreciate a bit of help to translate a few new strings. 🚀 We used a website to upload all the strings and screenshots of the app where the relevant strings are found to make the translation process easier for you! You can use this [link](https://crwd.in/posture-pal) to quickly make an account and fill out the missing strings. Thank you in advance and reach out if you have any other questions! It looks like there's only 4 strings missing for Hungarian.

**Comment by KristofKekesi** [comment]
Hi @vickipetrova!
Nice to hear about the new update. I'll translate the strings tomorrow. About the screenshots, wow, I really appreciate them!

**Comment by vickipetrova** [comment]
Awesome, thank you so much! @KristofKekesi

**Pull request merged**
