### PR TITLE
Vietnamese translation for v1.2 aka initial launch

### PR DESCRIPTION
**Pull request by rungxanh1995**
Hi Jordi,

I'd like to provide a Vietnamese translation for Posture Pal.

There's only 1 part where I'm not sure how to translate, that is in `appstore.strings` with App Store Keywords, what do "lumo" and "lift" mean exactly?

### CODE REVIEW

**Comment by jordibruin** [comment]
@rungxanh1995 thanks!! Those two words are names of hardware trackers ( competitors basically)

**Comment by jordibruin** [comment]
Don't forget to also update the readme @rungxanh1995

**Comment by rungxanh1995** [comment]
Definitely Jordi 👍🏻

**Comment by vickipetrova** [comment]
Hey 😊,
Thank you so much for translating Posture Pal 🦒! As promised here is your Promo Code for the Pro version: JW496HY9KXWM @rungxanh1995

**Comment by rungxanh1995** [comment]
Thank you Vicki 🥰

**Comment by vickipetrova** [comment]
No worries 😎

**Pull request merged**
