### PR TITLE
Add Norwegian translation

### PR DESCRIPTION
**Pull request by onmyway133**

### CODE REVIEW

**Comment by jordibruin** [comment]
Thanks buddy!

**Comment by jordibruin** [comment]
Don't forget to add yourself to the readme! @onmyway133

**Comment by vickipetrova** [comment]
Hey 😊,
Thank you so much for translating Posture Pal 🦒! As promised here is your Promo Code for the Pro version: Y6YHK3TTN6KL @onmyway133

**Comment by jordibruin** [comment]
@onmyway133 I added a few more sentences that are used in the new version if you have some time 🙂

**Comment by vickipetrova** [comment]
Hi again @onmyway133 ! 😊

Thank you for helping us make Posture Pal accessible in more languages. With our new update on the go, we’d really appreciate a bit of help to translate a few new strings. 🚀 We used a website to upload all the strings and screenshots of the app where the relevant strings are found to make the translation process easier for you! You can use this [link](https://crwd.in/posture-pal) to quickly make an account and fill out the missing strings. Thank you in advance and reach out if you have any other questions!

**Pull request merged**
