### PR TITLE
Added Turkish translations

### PR DESCRIPTION
**Pull request by ulusalomer**

### CODE REVIEW

**Comment by jordibruin** [comment]
Thanks so much!! @ulusalomer

**Comment by vickipetrova** [comment]
Hey 😊,
Thank you so much for translating Posture Pal 🦒! As promised here is your Promo Code for the Pro version: 9AMYTFMWAT4X @ulusalomer

**Comment by vickipetrova** [comment]
Hi again!
We added a few more sentences that are used in the new version. We’d really appreciate it if you have some time to translate those as well! 😄 @ulusalomer

**Comment by vickipetrova** [comment]
Hi again @ulusalomer ! 😊

Thank you for helping us make Posture Pal accessible in more languages. With our new update on the go, we’d really appreciate a bit of help to translate a few new strings. 🚀 It looks like Turkish is only missing around 10 strings. We used a website to upload all the strings and screenshots of the app where the relevant strings are found to make the translation process easier for you! You can use this [link](https://crwd.in/posture-pal) to quickly make an account and fill out the missing strings. Thank you in advance and reach out if you have any other questions!

**Comment by ulusalomer** [comment]
Dear Vicki,
Sorry for the late reply I was on vacation. I translated all the remaining
phrases, done!
Good luck with the new release.
Best,
Ömer

**Comment by vickipetrova** [comment]
Hi Ömer,

No worries! Thank you so much for helping out with the translations again!

**Pull request merged**
