### PR TITLE
Add Italian localisation

### PR DESCRIPTION
**Pull request by gianpispi**

### CODE REVIEW

**Comment by jordibruin** [comment]
Thanks @gianpispi !

If you have time later this week to also do the App Store text that would be even more amazing!
I forgot to commit that file 😅

**Comment by gianpispi** [comment]
Done in #30 :D

**Comment by vickipetrova** [comment]
Hey 😊,
Thank you so much for translating Posture Pal 🦒! As promised here is your Promo Code for the Pro version: TARFRMHKN3JY @gianpispi

**Comment by gianpispi** [comment]
Thank you, @vickipetrova! 😊

**Comment by jordibruin** [comment]
@gianpispi I added a few more sentences that are used in the new version if you have some time 🙂

**Pull request merged**
