### PR TITLE
Italian localization, update README 

### PR DESCRIPTION
**Pull request by TheDarkPyotr**

### CODE REVIEW

**Comment by jordibruin** [comment]
I'm going to combine this one with the translations that the other Italian person already did. Will go through them later! Thanks!!

**Comment by jordibruin** [comment]
@TheDarkPyotr

**Comment by vickipetrova** [comment]
Hey 😊,
Thank you so much for translating Posture Pal 🦒! As promised here is your Promo Code for the Pro version: RXTHWHEEM3NH @TheDarkPyotr

**Comment by vickipetrova** [comment]
Hi again!
We added a few more sentences that are used in the new version. We’d really appreciate it if you have some time to translate those as well! 😄 @TheDarkPyotr

**Comment by TheDarkPyotr** [comment]
yeah, no problem @vickipetrova

**Pull request closed without merging**
