### PR TITLE
Update Vietnamese translation

### PR DESCRIPTION
**Pull request by rungxanh1995**
As per your update on Mar 27, 2022 for Posture Pal new version

### CODE REVIEW

**Comment by jordibruin** [comment]
You're the best!

**Comment by vickipetrova** [comment]
Hi again @rungxanh1995 ! 😊

Thank you for helping us make Posture Pal accessible in more languages. With our new update on the go, we’d really appreciate a bit of help to translate a few new strings. 🚀 We used a website to upload all the strings and screenshots of the app where the relevant strings are found to make the translation process easier for you! You can use this [link](https://crwd.in/posture-pal) to quickly make an account and fill out the missing strings. Thank you in advance and reach out if you have any other questions!

**Comment by rungxanh1995** [comment]
@vickipetrova Hi Vicki, got your message and I've finished translating the latest additions to Vietnamese on Crowdin 👍. Have a good day!

**Comment by vickipetrova** [comment]
Awesome, thank you so much! @rungxanh1995

**Pull request merged**
