### PR TITLE
Added Portuguese (Brazil) localization

### PR DESCRIPTION
**Pull request by tfmart**

### CODE REVIEW

**Comment by jordibruin** [comment]
Thanks a lot @tfmart

**Comment by vickipetrova** [comment]
Hey 😊,
Thank you so much for translating Posture Pal 🦒! As promised here is your Promo Code for the Pro version: ELWP9MXEL9XA @tfmart

**Comment by vickipetrova** [comment]
Hi again!
We added a few more sentences that are used in the new version. We’d really appreciate it if you have some time to translate those as well! 😄 @tfmart

**Comment by vickipetrova** [comment]
Hi again @tfmart ! 😊

Thank you for helping us make Posture Pal accessible in more languages. With our new update on the go, we’d really appreciate a bit of help to translate a few new strings. 🚀 It looks like Portuguese(Brazil) is only missing around 10 strings. We used a website to upload all the strings and screenshots of the app where the relevant strings are found to make the translation process easier for you! You can use this [link](https://crwd.in/posture-pal) to quickly make an account and fill out the missing strings. Thank you in advance and reach out if you have any other questions!

**Comment by tfmart** [comment]
Hi @vickipetrova! I've just updated the strings!

**Comment by vickipetrova** [comment]
Thanks so much for helping out with the translations again!

**Pull request merged**
