### PR TITLE
Added Polish translation.

### PR DESCRIPTION
**Pull request by kslazinski**
- I didn't know meaning/context of "go,lumo,lift" keywords in /* App Store Keywords */, so I left these 3 words as is.
- Other translations seem to be OK, but it would be better to see the app and check if all the translations are correct in the context where they were used.

### CODE REVIEW

**Comment by vickipetrova** [comment]
Hey 😊,
Thank you so much for translating Posture Pal 🦒! As promised here is your Promo Code for the Pro version: JLWJ7M9HPK4M

**Comment by kslazinski** [comment]
Thank you! 🤩

**Comment by jordibruin** [comment]
@kslazinski I added a few more sentences that are used in the new version if you have some time to translate those as well 🙂

**Comment by kslazinski** [comment]
> @kslazinski I added a few more sentences that are used in the new version if you have some time to translate those as well 🙂 

@jordibruin No problem, I can take a look in a few days. I'm now on a family holiday. But will be back end of week

**Pull request merged**
