### PR TITLE
Translation to Bosnian language

### PR DESCRIPTION
**Pull request by nedimf**
Bosnian language is pretty similar to: Croatian and Serbian, difference is mostly in few words, but whoever speaks any of these language can understand everything said/written

### CODE REVIEW

**Comment by jordibruin** [comment]
I appreciate it! I don't think a lot of apps have Bosnian translation so this is really cool, thanks!

If you have time later this week to also do the App Store text that would be even more amazing!
I forgot to commit that file 😅

**Comment by jordibruin** [comment]
Also don't forget to add your name to the readme!

**Comment by nedimf** [comment]
Sure thing, just ping me when you have AppStore file uploaded 😄

**Comment by jordibruin** [comment]
@nedimf 
I noticed I did not correctly localise 11 strings from the onboarding. I've added them to localisable file for you language if you could have a look!

Also, I don't think I can actually translate the App Store listing into Bosnian so that won't be necessary! Thanks for offering though!

**Comment by nedimf** [comment]
@jordibruin no problem, although by this [article](https://support.oneskyapp.com/hc/en-us/articles/206919477-List-of-languages-supported-by-iTunes-App-Store-for-app-description) "Croatian" is supported, I can translate app listing to "Croatian"

**Pull request merged**
