### PR TITLE
Update Readme, Add missing word in german localization

### PR DESCRIPTION
**Pull request by FloWritesCode**

### CODE REVIEW

**Comment by vickipetrova** [comment]
Hey 😊,
Thank you so much for translating Posture Pal 🦒! As promised here is your Promo Code for the Pro version: YEHF3TNNHE39 @chFlorian

**Comment by vickipetrova** [comment]
Hi again!
We added a few more sentences that are used in the new version. We’d really appreciate it if you have some time to translate those as well! 😄 @chFlorian

**Comment by FloWritesCode** [comment]
> Hi again!
> We added a few more sentences that are used in the new version. We’d really appreciate it if you have some time to translate those as well! 😄 @chFlorian

Sure!

**Comment by vickipetrova** [comment]
Hi again @chFlorian ! 😊

Thank you for helping us make Posture Pal accessible in more languages. With our new update on the go, we’d really appreciate a bit of help to translate a few new strings. 🚀 German is only missing around 5 strings. We used a website to upload all the strings and screenshots of the app where the relevant strings are found to make the translation process easier for you! You can use this [link](https://crwd.in/posture-pal) to quickly make an account and fill out the missing strings. Thank you in advance and reach out if you have any other questions!

**Pull request merged**
