### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by jamesryu108**
Korean translation

### CODE REVIEW

**Comment by jordibruin** [comment]
Who is my favourite Korean person? @jamesryu108 is!!

**Comment by jordibruin** [comment]
Can you also add yourself to the readme? @jamesryu108

**Comment by jamesryu108** [comment]
Haha. Thanks. Yes, I will add myself.

**Comment by vickipetrova** [comment]
Hey 😊,
Thank you so much for translating Posture Pal 🦒! As promised here is your Promo Code for the Pro version: FRHFW9HWF3NE @jamesryu108

**Comment by jamesryu108** [comment]
Thank you so much!

**Comment by vickipetrova** [comment]
Hi again!
We added a few more sentences that are used in the new version. We’d really appreciate it if you have some time to translate those as well! 😄 @jamesryu108

**Comment by jordibruin** [comment]
@jamesryu108 I noticed that the App Store text wasn't translated yet. If you have some time that would be great, since the app got picked up by some Korean websites as well 🙂

**Comment by jamesryu108** [comment]
> 

Sure thing. @jordibruin I will do it today

**Comment by jordibruin** [comment]
Thanks @jamesryu108 😘

**Comment by vickipetrova** [comment]
Hi again @jamesryu108 ! 😊

Thank you for helping us make Posture Pal accessible in more languages. With our new update on the go, we’d really appreciate a bit of help to translate a few new strings. 🚀 Korean only has around 10-15 strings missing. We used a website to upload all the strings and screenshots of the app where the relevant strings are found to make the translation process easier for you! You can use this [link](https://crwd.in/posture-pal) to quickly make an account and fill out the missing strings. Thank you in advance and reach out if you have any other questions!

**Pull request merged**
