### PR TITLE
Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by TianhuiXu**
Modified the template with simplified Chinese translation.

Language: Simplified Chinese
Translator: Tianhui Xu
Twitter: https://twitter.com/xu_tianhuihui
Emoji: 🎋

### CODE REVIEW

**Comment by jordibruin** [comment]
Hi @TianhuiXu! Thanks a lot!!

**Comment by jordibruin** [comment]
@TianhuiXu I noticed I did not correctly localise 11 strings from the onboarding. I've added them to localisable file for you language if you could have a look!

**Comment by TianhuiXu** [comment]
Hi @jordibruin! I compared the difference and only noticed the newly-added 'super serious mode' and it looks good to me. Are there any other changes I should make?

**Comment by vickipetrova** [comment]
Hey 😊,
Thank you so much for translating Posture Pal 🦒! As promised here is your Promo Code for the Pro version: 7HWH6HYYPXXW @TianhuiXu

**Comment by jordibruin** [comment]
@TianhuiXu I'm just seeing your previous comment now. I think you got all of them back then 🙂 

I added a few more sentences that are used in the new version if you have some time to translate those as well!

**Comment by vickipetrova** [comment]
Hi again @TianhuiXu ! 😊

Thank you for helping us make Posture Pal accessible in more languages. With our new update on the go, we’d really appreciate a bit of help to translate a few new strings. 🚀 It looks like Simplified Chinese is only missing 1 string.  We used a website to upload all the strings and screenshots of the app where the relevant strings are found to make the translation process easier for you! You can use this [link](https://crwd.in/posture-pal) to quickly make an account and fill out the missing strings. Thank you in advance and reach out if you have any other questions!

**Pull request merged**
